export enum JudiInitialState {
  ACCOUNT_BALANCE = 'ACCOUNT_BALANCE',
  BUY = 'BUY',
  SELL = 'SELL',
  JUDI = 'JUDI',
  OPERATE_MY_MONEY = 'OPERATE_MY_MONEY',
  SYMBOL_PRICE = 'SYMBOL_PRICE',
}

export enum JudiState {
  INITIAL = 'INITIAL',
  ACCOUNT_BALANCE_SUCCESS = 'ACCOUNT_BALANCE_SUCCESS',
  ACCOUNT_BALANCE_FAILED = 'ACCOUNT_BALANCE_FAILED',
  LISTENING_MARKET = 'LISTENING_MARKET',
  HANDLE_BUY = 'HANDLE_BUY',
  HANDLE_SELL = 'HANDLE_SELL',
  HANDLE_BUY_SUCCESS = 'HANDLE_BUY_SUCCESS',
  HANDLE_SELL_SUCCESS = 'HANDLE_SELL_SUCCESS',
  PROCESSING_ORDER = 'PROCESSING_ORDER',
  SYMBOL_PRICE_SUCCESS = 'SYMBOL_PRICE_SUCCESS',
  SYMBOL_PRICE_FAILED = 'SYMBOL_PRICE_FAILED',
  INTENTION_TO_BUY = 'INTENTION_TO_BUY',
  INTENTION_TO_SELL = 'INTENTION_TO_SELL',
}

export enum JudiEvents {
  SUCCESS = 'SUCCESS',
  FAILURE = 'FAILURE',
  PROCESSING = 'PROCESSING',
}

export interface JudiEvent {
  initialState: JudiInitialState;
  state: JudiState;
  data: any;
}

export interface JudiConfig {
  symbol?: string;
  goodBuy?: number;
  goodSell?: number;
}
